### ISSUE TITLE
Unexpected keyword 'const' - Babel Error?

### ISSUE THREAD

**Issue by hvaughan3** [superwf/vuex-cache#12]
Receiving the following error on an iOS 9.3.2 device when using this plugin:

> Unexpected keyword 'const'. Const declarations are not supported in strict mode.

I assume it has to do with babel 7 configuration (as old Safari versions do not natively handle `const`). So would this be something we need to handle in then config of our project or is this something wrong in the plugin code? If so, any tips to help me accomplish that? I am lost when it comes to webpack and babel configs. Thanks!

**Comment by VitorLuizC** [comment]
You can fix using same suggestions as https://github.com/superwf/vuex-cache/issues/8#issuecomment-423168400.

**Comment by VitorLuizC** [comment]
@superwf maybe bundle down just UMD seems a huge problem, so I'll make another PR bundling down ESM and UMD modules

**Comment by superwf** [comment]
@VitorLuizC maybe I should use the umd format for main file for this package to make it more compatible?

**Comment by hvaughan3** [comment]
@VitorLuizC Think I understand now. Appreciate your help.

**Comment by VitorLuizC** [comment]
@superwf I think we have to bundle down ESM, but keep it as ESM.

I've been doing this for a while in my libraries using https://github.com/egoist/bili. It bundle to multiple module outputs and is very simple to setup and use.

Ex.
https://github.com/VitorLuizC/vue-uuid
