### ISSUE TITLE
Should we dismiss action errors?

### ISSUE THREAD

**Issue by VitorLuizC** [superwf/vuex-cache#18]
Cache promise rejections is a common question (#7, #16), and I believe we need to discuss if we need cache actions errors or dismiss them?

### Pros
- Handle `vue-cache` rejections on our stores is undesirable behavior;
- It'll cause some errors if is not well handled;
- Users don't know about cache rejections, because is not documented anywhere;

### Cons
- It can add complexity and increase module size;
- Intercepting the promise is an invasive procedure;

**Comment by wcxaa** [comment]
I think its better to let user retry then to always return a rejection when it rejected by network errors .

**Comment by VitorLuizC** [comment]
@wcxaa totally agree, seems pretty smart to cache only resolved promises.

**Comment by VitorLuizC** [comment]
@superwf If you agree I can make the PR with this change, but it have to be a breaking change and we need to bump to version 2.

**Comment by superwf** [comment]
@VitorLuizC just do what you could to make it better. In this year my team change to use react for company jobs and I did not use vue for more than a year. So I am glad to accept  suggestion from real vue user.

**Comment by VitorLuizC** [comment]
@superwf I really like this project and this would be such nice!
