### ISSUE TITLE
Remove peerDependencies

### ISSUE THREAD

**Issue by VitorLuizC** [superwf/vuex-cache#2]
I'm using Vuex 3 for a while with `vuex-cache` and today I realize `vuex-cache` is warning about incorrect peer depedency.

```
warning " > vuex-cache@1.0.0" has incorrect peer dependency "vuex@^2.2.1".
```

Adding 3.x to peerDependencies would solve it, because 3.0 doesn't break plugins and dispatch APIs, but looking at Vuex 1 docs you can also notice plugins and dispatch APIs are same too. So, `vuex-cache` is compatible with all vuex versions and there's no reason to keep a `peerDependencies` checking it.

> I'm just ignoring Vuex 0.x...

- Vuex 3 release details:
  - https://github.com/vuejs/vuex/releases/tag/v3.0.0
- Vuex 1 docs about plugins and actions/dispatches:
  - https://github.com/vuejs/vuex/blob/1.0/docs/en/plugins.md
  - https://github.com/vuejs/vuex/blob/1.0/docs/en/actions.md

**Comment by VitorLuizC** [comment]
I forgot about checking Vue version and since `vuex-cache` handle just Vuex we can remove it too.

**Comment by VitorLuizC** [comment]
@superwf 
This is still warning. Can you publish changes to npm?

**Comment by superwf** [comment]
published~
