### ISSUE TITLE
Exclude Timeout Setting From Cache Key Name

### ISSUE THREAD

**Issue by hvaughan3** [superwf/vuex-cache#20]
When passing a timeout value in the Vuex call like so:

    await this.$store.cache.dispatch('customer/getInfo', {
        timeout: SettingsConstants.longCacheTimeout
    })

It looks like it is adding the timeout value to the name of the cache key. So after making that call and then running `this.$store.cache.entries()`, I see that the cache entry name is set to:

    customer/getInfo:{"timeout":21600000}

This is kind of annoying because now I will have to pass the timeout value to all calls, such as `.has()` and `.delete()`.

For example, the following would not find or delete the cache key (which was unexpected):

    this.$store.cache.has('customer/getInfo')
    this.$store.cache.delete('customer/getInfo')

So I would have to do this instead:

    this.cache.has('customer/getInfo', {
        timeout: SettingsConstants.longCacheTimeout
    })

    this.cache.delete('customer/getInfo', {
        timeout: SettingsConstants.longCacheTimeout
    })

Could the settings object be excluded from the cache key name while still including the Vuex params in the name? Thanks.

**Comment by VitorLuizC** [comment]
Maybe you're using timeout in a wrong way.

There are just two ways to setup timeout setting.

```js
store.cache.dispatch({
  type: 'customer/getInfo',
  timeout: SettingsConstants.longCacheTimeout,
  // payload: { ... }
})
// AND
store.cache.dispatch(ACTION_NAME, undefined /* payload */, {
  timeout: SettingsConstants.longCacheTimeout
})
```

**Comment by VitorLuizC** [comment]
Neither of those use `timeout` as dispatch property, but as `DispatchOptions`. Can you check if your timeout is really working?

**Comment by hvaughan3** [comment]
Ahh ok let me check on that. I bet I just need to add undefined! Will get back to you here in an hour or so. Thank you very much.
