### ISSUE TITLE
vuex-cache with Nuxt.js

### ISSUE THREAD

**Issue by nathanchase** [superwf/vuex-cache#26]
How might one go about using vuex-cache with [Nuxt.js](https://github.com/nuxt/nuxt.js)?

[The way the Vuex store works with Nuxt](https://nuxtjs.org/guide/vuex-store/) doesn't support a way to use the `plugins: [vuexCache]` syntax, so I was wondering if there might be an alternate way to instantiate vuex-cache with the store?

A similar plugin ([vuex-persistedstate](https://github.com/robinvdvleuten/vuex-persistedstate)) has this as a solution: 
```
// nuxt.config.js

...
plugins: [{ src: '~/plugins/localStorage.js', ssr: false }]
...
// ~/plugins/localStorage.js

import createPersistedState from 'vuex-persistedstate'

export default ({store}) => {
  window.onNuxtReady(() => {
    createPersistedState({
        key: 'yourkey',
        paths: [...]
        ...
    })(store)
  })
}
```
Perhaps a similar method might work for vuex-cache?

**Comment by VitorLuizC** [comment]
The same method actually works for `vuex-cache` too.

**`nuxt.config.js`**
```js
module.exports = {
  ...,
  plugins: [
    { src: '~/plugins/vuex-cache.js', ssr: false },
  ]
};
```
**`plugins/vuex-cache.js`**
```js
import createCache from 'vuex-cache';

export default function install ({ store }) {
  const options = { timeout: 1000 * 60 };

  window.onNuxtReady(() => createCache(options)(store));
}
```

**Comment by VitorLuizC** [comment]
@superwf I'll create a section with this example of how to use vuex-cache on Nuxt.js. This would be a part of issue #21.
