### ISSUE TITLE
Android 4.4.2 Map is not defined error

### ISSUE THREAD

**Issue by hvaughan3** [superwf/vuex-cache#31]
Using the latest version of the library, I receive the following error on an Android 4.4.2 WebView. Wondering if this was caused by recent changes to babel configs (#23)?

    Uncaught ReferenceError: Map is not defined

**Comment by VitorLuizC** [comment]
You have to use Map polyfill.

**Comment by hvaughan3** [comment]
@VitorLuizC Is this a new requirement? I did not have this problem using older versions of the plugin.

**Comment by VitorLuizC** [comment]
This is a requirement since version 1.0. You can see a notice about It on README.md

**Comment by hvaughan3** [comment]
@VitorLuizC Thanks for your help!
