### ISSUE TITLE
Use with Store Module

### ISSUE THREAD

**Issue by bradley-varol** [superwf/vuex-cache#34]
I have a store module named 'cache', like so:
```js
import cache from '@/modules/cache/_store';
export default new Vuex.Store({
    modules: {
        cache,
    },
    strict: true,
});
```

But using `this.$store.cache.dispatch('cache/doSomething');` from within a component throws a `"TypeError: this.$store.cache is undefined"`

_Originally posted by @bradley-varol in https://github.com/superwf/vuex-cache/issues/9#issuecomment-469276664_

**Comment by VitorLuizC** [comment]
The only solution I see here is rename `cache` to `$cache` or something like that.

We can't prevent Vuex to overwrite our cache instance with your cache module.

Something similar can happen if you create a module with name `dispatch`, you can't access it like other modules.
```js
this.$store.dispatch.dispatch('action');
// throws TypeError: this.$store.dispatch.dispatch is not a function
```

**Comment by bradley-varol** [comment]
I thought that the module name might be the problem but didn't have time to test.
I'll rename my module.

Cheers Vitor 😊

**Comment by bradley-varol** [comment]
I actually didn't know that `this.$store.module.dispatch('action')` is the same as `this.$store.dispatch('module/action')`! 😊

On 6 Mar 2019 22:33, Vitor Luiz Cavalcanti <notifications@github.com> wrote:

The only solution I see here is rename cache to $cache or something like that.

We can't prevent Vuex to overwrite our cache instance with your cache module.

Something similar can happen if you create a module with name dispatch, you can't access it like other modules.

this.$store.dispatch.dispatch('action');
// throws TypeError: this.$store.dispatch.dispatch is not a function

**Comment by VitorLuizC** [comment]
So, can we close this issue?
