### ISSUE TITLE
Vuex-cache for Nuxtjs -> Cannot read property 'dispatch' of undefined

### ISSUE THREAD

**Issue by standfv** [superwf/vuex-cache#36]
I'm did read docs.
I'm create plugins/vuex-cache.js
End config nuxt.config.js

I use this.$store.cache.dispatch("modulesA/actionA") in folder components.
F5 router => alert " Cannot read property 'dispatch' of undefined"
? How to fix?

**Comment by VitorLuizC** [comment]
Maybe this is happening before `onNuxtReady`.

Can you provide a project on CodeSandbox or a repository to reproduce this bug?

**Comment by VitorLuizC** [comment]
I couldn't reproduce this issue, so I'm closing it.

**Comment by leeovery** [comment]
Im getting the same issue here

**Comment by VitorLuizC** [comment]
@leeovery Can you provide a project on CodeSandbox or a repository to reproduce this bug?

**Comment by baumak** [comment]
use it like usual nuxt vuex store plugin 
https://nuxtjs.org/docs/2.x/directory-structure/store#plugins-in-the-store
 
In Nuxt i did like this below
in store/index.js 
`
import createCache from 'vuex-cache'; `
`const options = {
          timeout: 30000 // Equal to 30 seconds in milliseconds.
      };`
`export const plugins = [createCache(options)] `
