### ISSUE TITLE
Complete example how to use vuex-cache

### ISSUE THREAD

**Issue by phlegx** [superwf/vuex-cache#38]
Hi!

I miss a complete working example how to use `vuex-cache`. Can this be added to the documentation or a separate repo please?

Thx

**Comment by VitorLuizC** [comment]
You just have to install and use `store` methods thought `store.cache` namespace.

```js
store.cache.dispatch('getUsers', { companyID: '1' }, {
  timeout: 10000 // Optionally define a timeout to cache.
});
```

**Comment by phlegx** [comment]
So, I don't need to implement vuex states, getters, mutations etc. but only the actions?

**Comment by VitorLuizC** [comment]
Yeap, it just caches action dispatches.

Pretty similar to memoization libraries.

**Comment by phlegx** [comment]
Thx!
