### ISSUE TITLE
Export StoreCache interface so that it can be mocked

### ISSUE THREAD

**Issue by kierans** [superwf/vuex-cache#41]
In my Component tests, I want to mock/fake my Vuex `Store` and the `cache` property to make sure that my component is integrating with my actions correctly.

However because the `StoreCache` interface isn't exported I can't create a typesafe mock/fake.

**Comment by VitorLuizC** [comment]
Published under version 3.1.1

https://github.com/superwf/vuex-cache/blob/master/CHANGELOG.md#311
