### ISSUE TITLE
When dispatching `this` not bound correctly

### ISSUE THREAD

**Issue by kierans** [superwf/vuex-cache#43]
This issue relates to #41 as I'm wanting to mock/fake the `StoreCache` for Component tests.

When dispatching (see vuex-cache.js#L297, #L305) `this` is bound to the `store` not the store cache. Given the `cache.dispatch` method doesn't use `this`, this bug probably hasn't surfaced yet. However when mocking/faking `store.cache` the cache methods are being called with the wrong `this`.

**Comment by VitorLuizC** [comment]
Published under version 3.1.1

https://github.com/superwf/vuex-cache/blob/master/CHANGELOG.md#311
