### ISSUE TITLE
Webpack build error

### ISSUE THREAD

**Issue by iabok** [superwf/vuex-cache#8]
Each time i run a production build, the build fails on Vue-cache module with this error. 
`UglifyJs
       Unexpected token: operator (>) [./node_modules/vuex-cache/index.module.js:1,0][app.js:43610,17]`

**Comment by VitorLuizC** [comment]
**module** bundle uses es2015 syntax. You can bundle it down before minify or use something like `babel-minify` instead

**Comment by VitorLuizC** [comment]
You can also target `index.umd.js` module, which is bundled as ES5

**Comment by iabok** [comment]
Thank you.

**Comment by superwf** [comment]
thanks @VitorLuizC
