### ISSUE TITLE
Vuex cache in a module mode

### ISSUE THREAD

**Issue by wkornilow** [superwf/vuex-cache#9]
Could you please explain how to use this plugin with a Vuex in a module mode?

**Comment by bradley-varol** [comment]
I'm struggling with this...
I have a store like so:
```js
import cache from '@/modules/cache/_store';
export default new Vuex.Store({
    modules: {
        cache,
    },
    strict: true,
});
```

`this.$store.cache.dispatch('cache/doSomething');` throws a `"TypeError: this.$store.cache is undefined"`
